name: muze
description: Muze app

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  # Flutter
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # Structure
  flutter_bloc: ^8.1.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  json_annotation: ^4.8.1

  # Requests
  http: ^1.1.0
  intl: ^0.18.0
  path: ^1.8.3

  # Local storage
  shared_preferences: ^2.2.2

  # Router
  go_router: ^12.1.0

  # Fonts
  google_fonts: ^6.1.0

  # Animations
  lottie: ^2.6.0
  marquee: ^2.2.3
  flutter_bounceable: ^1.1.0

  # Launcher icon
  flutter_launcher_icons: ^0.13.1

  # Custom textfield
  pinput: ^3.0.1

  # WebView
  webview_flutter: ^4.4.2

  # Image
  flutter_svg: ^2.0.9
  gif_view: ^0.4.0
  cached_network_image: ^3.3.1

  # Card swiper
  flutter_card_swiper: ^6.0.0

  # Audio
  just_audio: ^0.9.36

  # List
  inview_notifier_list: ^3.0.0

  # Authentication Thirdparty
  oauth2_client: ^3.2.2
  flutter_web_auth_2: ^2.2.1

  # Launcher url
  url_launcher: ^6.1.14

  # Device info
  device_info_plus: ^9.1.1
  skeletonizer: ^1.0.1

  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/images/images/
    - assets/images/buttons/
    - assets/images/icons/
    - assets/images/logos/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logos/muze_logo.png"
